### ISSUE TITLE
PlanetScale の無料プランが廃止されるため移行先を調査する

### ISSUE THREAD

**Issue by Kazuya-Sakamoto** [Kazuya-Sakamoto/lgtm-kinako-api#52]
## 概要
https://planetscale.com/blog/planetscale-forever
↑のあるように**2024 年 4 月 8 日**に無料のプランhobbyが廃止される

## 対応内容
- PlanetScaleからの移行先を考える
  - [Render.com + PlanetScale デプロイ手順](https://zenn.dev/ddpmntcpbr/articles/rails-render-planetscale#%EF%BC%88%E2%80%BB2024%E5%B9%B43%E6%9C%887%E6%97%A5%E8%BF%BD%E8%A8%98%EF%BC%89%E9%87%8D%E8%A6%81%E4%BA%8B%E9%A0%85)

**Comment by hooopo** [comment]
TiDB Serverless is free up to 5GB and 50M Request Units (RUs) without the need to enter a credit card. It is compatible with MySQL, so migrating from PlanetScale to TiDB Serverless should be very easy.

**Comment by Kazuya-Sakamoto** [comment]
@hooopo 
Thank you for your suggestion! We will consider TiDB Serverless, especially given its compatibility with MySQL and the ease of migration from PlanetScale. We appreciate your input!

**Comment by Kazuya-Sakamoto** [comment]
比較がわかりやすい
- [無料枠が無くなったPlanetScale の代替DBを検討する。](https://qiita.com/Kenta_Kobayashi/items/ba445245ecd357dd19d7)

**Comment by Kazuya-Sakamoto** [comment]
[Neon](https://neon.tech/) 良さげかも。ただリージョンで一番近いところでシンガポールだから少しパフォーマンスの懸念はある。
- [【個人開発】無料DBを求めてPlanetScaleからNeonに移行したら快適だった話](https://qiita.com/nuko-suke/items/e940ff8ccde35d09f668)

**Comment by Kazuya-Sakamoto** [comment]
- [postgresql から mysqlに移行](https://github.com/Kazuya-Sakamoto/lgtm-kinako-api/pull/39/files)

↑で 一度mysqlに移行をしたが今回Neonを使用するのであれば戻す必要がある

**Comment by Kazuya-Sakamoto** [comment]
- mysql から変更しないのであれば [TiDB](https://qiita.com/bohnen/items/de7557078f64891763ac) が良さそうかな

**Comment by Kazuya-Sakamoto** [comment]
https://github.com/pingcap/tidb

**Comment by Kazuya-Sakamoto** [comment]
一旦 TiDBに移行完了しました🎉

使用感や細かい設定については別途対応する。
